  // File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7BWjZgmc9_65G5bNmbLashwQii7jf1tI',
    appId: '1:580876700157:web:2195ca65a92e9b42357194',
    messagingSenderId: '580876700157',
    projectId: 'tearberg-8fba6',
    authDomain: 'tearberg-8fba6.firebaseapp.com',
    storageBucket: 'tearberg-8fba6.appspot.com',
    measurementId: 'G-Q3CYN7EHLN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnKbewoE-bOG3tyy-5Hx474voZ81X2MJc',
    appId: '1:580876700157:android:b23dd10aee177875357194',
    messagingSenderId: '580876700157',
    projectId: 'tearberg-8fba6',
    storageBucket: 'tearberg-8fba6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDg-u_xhq4hiGpPcTQq87avjqrUTztajhM',
    appId: '1:580876700157:ios:fbef171bd25fdc82357194',
    messagingSenderId: '580876700157',
    projectId: 'tearberg-8fba6',
    storageBucket: 'tearberg-8fba6.appspot.com',
    androidClientId: '580876700157-7ga09k6farcgd6oc0e0k3pvpi699o0fk.apps.googleusercontent.com',
    iosClientId: '580876700157-0u0k5rti84juf188htmdqfjg1lb9p1sl.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginpagedesign',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDg-u_xhq4hiGpPcTQq87avjqrUTztajhM',
    appId: '1:580876700157:ios:f9e0c09d4daccc48357194',
    messagingSenderId: '580876700157',
    projectId: 'tearberg-8fba6',
    storageBucket: 'tearberg-8fba6.appspot.com',
    androidClientId: '580876700157-7ga09k6farcgd6oc0e0k3pvpi699o0fk.apps.googleusercontent.com',
    iosClientId: '580876700157-55hk3kutlend1r6hvtbhjrh9f78vsl77.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginpagedesign.RunnerTests',
  );
}
